LOAD DATA LOCAL INFILE "Users.csv"
INTO TABLE Users
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "Availability.csv"
INTO TABLE Availability
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "ProfRoom.csv"
INTO TABLE ProfRoom
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "Courses.csv"
INTO TABLE Courses
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "Teach.csv"
INTO TABLE Teach
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "appointment.csv"
INTO TABLE appointment
FIELDS TERMINATED BY ",";